#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd $DIR &>/dev/null

cat <&0 > ../manager/manager.yaml

${KUSTOMIZE} build . 2>/dev/null

popd &>/dev/null
