apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    envTemplate:
          template: "{{.IMAGE_NAME}}"
  cluster: {}
  artifacts:
    - image: redhat-marketplace-operator
      custom:
        buildCommand: ./scripts/skaffold_build.sh
        dependencies:
          paths:
            - ./cmd
            - ./pkg
            - ./assets
            - ./deploy/chart
          ignore:
            - vendor/**
deploy:
  kubectl:
    manifests:
      - deploy/crds/*cr.yaml
      - deploy/*.yaml
    flags:
      disableValidation: true
