apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: redhat-marketplace-operator
build:
  local:
    useBuildkit: true
    concurrency: 2
  tagPolicy:
    customTemplate:
      template: '{{ .VERS }}-{{ .GC }}'
      components:
        - name: VERS
          envTemplate:
            template: '{{.VERSION}}'
        - name: GC
          gitCommit:
            variant: AbbrevCommitSha
  artifacts:
    - image: redhat-marketplace-operator
      context: .
      custom:
        buildCommand: ARCHS=amd64 make vet docker-build
        dependencies:
          paths:
            - go.mod
            - go.sum
            - 'main.go'
            - 'apis/**'
            - 'controllers/**'
            - 'pkg/**'
            - 'assets/**'
            - Dockerfile
          ignore:
            - './**/*_test.go'
    - image: redhat-marketplace-reporter
      context: ../reporter/v2
      custom:
        buildCommand: ARCHS=amd64 make vet docker-build
        dependencies:
          paths:
            - go.mod
            - go.sum
            - cmd/**
            - pkg/**
            - Dockerfile
          ignore:
            - './**/*_test.go'
    - image: redhat-marketplace-metric-state
      context: ../metering/v2
      custom:
        buildCommand: ARCHS=amd64 make vet docker-build
        dependencies:
          paths:
            - go.mod
            - go.sum
            - cmd/**
            - internal/**
            - pkg/**
            - './**/*.go'
            - Dockerfile
          ignore:
            - './**/*_test.go'
    - image: redhat-marketplace-authcheck
      context: ../authchecker/v2
      custom:
        buildCommand: ARCHS=amd64 make vet docker-build
        dependencies:
          paths:
            - go.mod
            - go.sum
            - cmd/**
            - pkg/**
            - Dockerfile
          ignore:
            - '**/*_test.go'
    - image: redhat-marketplace-data-service
      context: ../airgap/v2
      custom:
        buildCommand: ARCHS=amd64 make vet docker-build
        dependencies:
          paths:
            - go.mod
            - go.sum
            - apis/**
            - cmd/server/**
            - pkg/**
            - internal/**
            - Dockerfile
          ignore:
            - '**/*_test.go'
deploy:
  helm:
    releases:
      - name: rhm-operator
        namespace: openshift-redhat-marketplace
        artifactOverrides:
          operatorImage: redhat-marketplace-operator
          reporterImage: redhat-marketplace-reporter
          metricStateImage: redhat-marketplace-metric-state
          authCheckImage: redhat-marketplace-authcheck
          dqLiteImage: redhat-marketplace-data-service
        wait: false
        upgradeOnChange: true
        chartPath: ./config/helm-wrapper
        setValueTemplates:
          'devEnvVars[0].name': 'RELATED_IMAGE_METERDEF_FILE_SERVER'
          'devEnvVars[0].value': '{{.IMAGE_REGISTRY}}/rhm-meterdefinition-file-server:v1'
        valuesFiles:
          - ./config/helm-wrapper/values.yaml
          - ./config/helm-wrapper/devValues.yaml
    flags:
      install:
        - --post-renderer
        - config/helm-wrapper/kustomize
      upgrade:
        - --post-renderer
        - config/helm-wrapper/kustomize
portForward:
  - resourceType: StatefulSet
    resourceName: prometheus-rhm-marketplaceconfig-meterbase
    port: 9090
  - resourceType: Deployment
    resourceName: rhm-metric-state
    port: 8080
