apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redhat-marketplace-operator
  namespace: openshift-redhat-marketplace
spec:
  channel: stable
  installPlanApproval: Manual
  name: redhat-marketplace-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
