kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watch-keeper-binding
subjects:
- kind: ServiceAccount
  name: watch-keeper
  namespace: system
roleRef:
  kind: ClusterRole
  name: watch-keeper
  apiGroup: rbac.authorization.k8s.io
