apiVersion: batch/v1
kind: CronJob
metadata:
  name: rhm-meter-report-upload
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: rhm-meter-report-upload
            app.kubernetes.io/instance: rhm-meter-report-upload
            app.kubernetes.io/part-of: ibm-metrics-operator
            app.kubernetes.io/managed-by: operator
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                          - amd64
                          - ppc64le
                          - s390x
          securityContext: 
            runAsNonRoot: true              
          serviceAccount: ibm-metrics-operator-reporter
          restartPolicy: Never
          schedule: '*/10 * * * *'
          containers:
          - name: reporter
            image: redhat-markplace-reporter
            imagePullPolicy: Always
            # additional args are added in factory
            args:
              - 'reconcile'
            env:
              - name: JOB_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['job-name']
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: IS_DISCONNECTED
                value: "false"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true