// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package metric_generator

import (
	"github.com/redhat-marketplace/redhat-marketplace-operator/pkg/controller"
	"github.com/redhat-marketplace/redhat-marketplace-operator/pkg/managers"
	"github.com/redhat-marketplace/redhat-marketplace-operator/pkg/utils/reconcileutils"
	"sigs.k8s.io/controller-runtime/pkg/client/config"
	"time"
)

import (
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)

// Injectors from wire.go:

func NewServer(opts *Options) (*Service, error) {
	restConfig, err := config.GetConfig()
	if err != nil {
		return nil, err
	}
	restMapper, err := managers.NewDynamicRESTMapper(restConfig)
	if err != nil {
		return nil, err
	}
	opsSrcSchemeDefinition := controller.ProvideOpsSrcScheme()
	monitoringSchemeDefinition := controller.ProvideMonitoringScheme()
	olmV1SchemeDefinition := controller.ProvideOLMV1Scheme()
	olmV1Alpha1SchemeDefinition := controller.ProvideOLMV1Alpha1Scheme()
	localSchemes := controller.ProvideLocalSchemes(opsSrcSchemeDefinition, monitoringSchemeDefinition, olmV1SchemeDefinition, olmV1Alpha1SchemeDefinition)
	scheme, err := managers.ProvideScheme(restConfig, localSchemes)
	if err != nil {
		return nil, err
	}
	clientOptions := getClientOptions()
	cache, err := managers.ProvideNewCache(restConfig, restMapper, scheme, clientOptions)
	if err != nil {
		return nil, err
	}
	client, err := managers.ProvideClient(restConfig, restMapper, scheme, cache, clientOptions)
	if err != nil {
		return nil, err
	}
	options := ConvertOptions(opts)
	logger := _wireLoggerValue
	clientCommandRunner := reconcileutils.NewClientCommand(client, scheme, logger)
	collectorRefreshRate := _wireCollectorRefreshRateValue
	stopCollector := _wireStopCollectorValue
	collector := NewMeterCollector(clientCommandRunner, collectorRefreshRate, cache, stopCollector)
	service := &Service{
		k8sclient: client,
		opts:      options,
		collector: collector,
	}
	return service, nil
}

var (
	_wireLoggerValue               = log
	_wireCollectorRefreshRateValue = CollectorRefreshRate(time.Minute * 5)
	_wireStopCollectorValue        = collectorStop
)
