#!/bin/bash

if [ "$KUSTOMIZE" == "" ]; then
    KUSTOMIZE=$(which kustomize)
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

pushd $DIR &> /dev/null

cat <&0 > ../manager/manager.yaml

${KUSTOMIZE} build --stack-trace .

popd &> /dev/null
