apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  selector:
    matchLabels:
      redhat.marketplace.com/name: redhat-marketplace-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        redhat.marketplace.com/name: redhat-marketplace-operator
    spec:
      containers:
        - name: manager
          args:
            - --enable-leader-election
          image: {{ .Values.operatorImage }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: OPERATOR_NAME
              value: redhat-marketplace-operator
            - name: RELATED_IMAGE_REPORTER
              value: {{ .Values.reporterImage }}
            - name: RELATED_IMAGE_METRIC_STATE
              value: {{ .Values.metricStateImage }}
            - name: RELATED_IMAGE_AUTHCHECK
              value: {{ .Values.authCheckImage }}
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OLM_OWNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['olm.owner']
            - name: OLM_OWNER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['olm.owner.namespace']
            - name: OLM_OWNER_KIND
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['olm.owner.kind']
          volumeMounts:
          - name: redhat-marketplace-controller-manager-config
            mountPath: "/config"
            readOnly: true
      terminationGracePeriodSeconds: 10
      serviceAccountName: operator
      volumes:
      - name: redhat-marketplace-controller-manager-config
        configMap:
          name: redhat-marketplace-controller-manager-config
          optional: true
