// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.ibm.com/symposium/redhat-marketplace-operator/cmd/managers"
	"github.ibm.com/symposium/redhat-marketplace-operator/pkg/controller"
)

// Injectors from wire.go:

func initializeMarketplaceController() *managers.ControllerMain {
	marketplaceController := controller.ProvideMarketplaceController()
	controllerFlagSet := controller.ProvideControllerFlagSet()
	opsSrcSchemeDefinition := managers.ProvideOpsSrcScheme()
	controllerMain := makeMarketplaceController(marketplaceController, controllerFlagSet, opsSrcSchemeDefinition)
	return controllerMain
}
