apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api
  labels:
    redhat.marketplace.com/name: ibm-data-reporter-operator
rules:
- nonResourceURLs:
  - "/v1/status"
  verbs:
  - get
- nonResourceURLs:
  - "/v1/event"
  verbs:
  - create
  - post
