#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

pushd $DIR &>/dev/null

cat <&0 >../manager/manager.yaml

${KUSTOMIZE} build . | yq ea 'select(.kind != "Namespace")' -

popd &>/dev/null
