#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

if [[ "$KUSTOMIZE" == "" ]]; then
  KUSTOMIZE=$(which kustomize)
fi

if [[ "$YQ" == "" ]]; then
  YQ=$(which yq)
fi

pushd $DIR &>/dev/null

cat <&0 >../manager/manager.yaml

${KUSTOMIZE} build . | ${YQ} ea 'select(.kind != "Namespace")' -

popd &>/dev/null
