# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - bearerTokenSecret:
        key: token
        name: redhat-marketplace-servicemonitor-metrics-reader
      path: /metrics
      port: https
      scheme: https
  selector:
    matchLabels:
      control-plane: controller-manager
      redhat.marketplace.com/name: redhat-marketplace-operator
