package reconcileutils

// Code generated by github.com/launchdarkly/go-options.  DO NOT EDIT.

import (
	"k8s.io/apimachinery/pkg/runtime"
)

type ApplyCreateActionOptionFunc func(c *createActionOptions) error

func (f ApplyCreateActionOptionFunc) apply(c *createActionOptions) error {
	return f(c)
}

func newCreateActionOptions(options ...CreateActionOption) (createActionOptions, error) {
	var c createActionOptions
	err := applyCreateActionOptionsOptions(&c, options...)
	return c, err
}

func applyCreateActionOptionsOptions(c *createActionOptions, options ...CreateActionOption) error {
	c.WithAddOwner = nil
	for _, o := range options {
		if err := o.apply(c); err != nil {
			return err
		}
	}
	return nil
}

type CreateActionOption interface {
	apply(*createActionOptions) error
}

func CreateWithPatch(o PatchAnnotator) ApplyCreateActionOptionFunc {
	return func(c *createActionOptions) error {
		c.WithPatch = o
		return nil
	}
}

func CreateWithAddOwner(o runtime.Object) ApplyCreateActionOptionFunc {
	return func(c *createActionOptions) error {
		c.WithAddOwner = o
		return nil
	}
}
