apiVersion: marketplace.redhat.com/v1beta1
kind: MeterDefinition
metadata:
  name: prometheus-user-workload-uptime
  namespace: openshift-user-workload-monitoring
spec:
  group: marketplace.redhat.com
  kind: Pod
  meters:
    - aggregation: avg
      metricId: prometheus-user-workload-uptime
      name: prometheus-user-workload-uptime
      period: 24h
      query: avg_over_time(up{job="prometheus-user-workload"}[5m])
      workloadType: Pod
      metricType: infrastructure
  resourceFilters:
    - label:
        labelSelector:
          matchLabels:
            prometheus: user-workload
      workloadType: Pod
