// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package reporter

import (
	"context"
	"github.com/redhat-marketplace/redhat-marketplace-operator/reporter/v2/pkg/dataservice"
	"github.com/redhat-marketplace/redhat-marketplace-operator/v2/pkg/managers"
	"github.com/redhat-marketplace/redhat-marketplace-operator/v2/pkg/prometheus"
	"github.com/redhat-marketplace/redhat-marketplace-operator/v2/pkg/utils/reconcileutils"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/record"
)

// Injectors from wire.go:

func NewTask(ctx context.Context, reportName ReportName, taskConfig *Config) (TaskRun, error) {
	config := taskConfig.K8sRestConfig
	restMapper, err := managers.NewDynamicRESTMapper(config)
	if err != nil {
		return nil, err
	}
	scheme := provideScheme()
	simpleClient, err := managers.ProvideSimpleClient(config, restMapper, scheme)
	if err != nil {
		return nil, err
	}
	logrLogger := _wireLoggerValue
	clientCommandRunner := reconcileutils.NewClientCommand(simpleClient, scheme, logrLogger)
	uploaders, err := ProvideUploaders(ctx, clientCommandRunner, simpleClient, logrLogger, taskConfig)
	if err != nil {
		return nil, err
	}
	uploader, err := ProvideUploader(uploaders)
	if err != nil {
		return nil, err
	}
	task := &Task{
		ReportName: reportName,
		CC:         clientCommandRunner,
		K8SClient:  simpleClient,
		Config:     taskConfig,
		K8SScheme:  scheme,
		Uploader:   uploader,
	}
	return task, nil
}

var (
	_wireLoggerValue = logger
)

func NewEventBroadcaster(erConfig *Config) (record.EventBroadcaster, func(), error) {
	config := erConfig.K8sRestConfig
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return nil, nil, err
	}
	eventBroadcaster, cleanup := provideReporterEventBroadcaster(clientset)
	return eventBroadcaster, func() {
		cleanup()
	}, nil
}

func NewReporter(ctx context.Context, task *Task) (*MarketplaceReporter, error) {
	config := task.Config
	simpleClient := task.K8SClient
	scheme := task.K8SScheme
	logrLogger := _wireLogrLoggerValue
	clientCommandRunner := reconcileutils.NewClientCommand(simpleClient, scheme, logrLogger)
	reportName := task.ReportName
	meterReport, err := getMarketplaceReport(ctx, clientCommandRunner, reportName)
	if err != nil {
		return nil, err
	}
	marketplaceConfig, err := getMarketplaceConfig(ctx, clientCommandRunner)
	if err != nil {
		return nil, err
	}
	service, err := getPrometheusService(ctx, meterReport, clientCommandRunner, config)
	if err != nil {
		return nil, err
	}
	servicePort, err := getPrometheusPort(config, service)
	if err != nil {
		return nil, err
	}
	prometheusAPISetup := providePrometheusSetup(config, meterReport, service, servicePort)
	prometheusAPI, err := prometheus.NewPrometheusAPIForReporter(prometheusAPISetup)
	if err != nil {
		return nil, err
	}
	v, err := getMeterDefinitionReferences(ctx, meterReport, simpleClient)
	if err != nil {
		return nil, err
	}
	dataBuilder, err := ProvideDataBuilder(config, logrLogger)
	if err != nil {
		return nil, err
	}
	reportWriter, err := ProvideWriter(config, marketplaceConfig, logrLogger)
	if err != nil {
		return nil, err
	}
	marketplaceReporter, err := NewMarketplaceReporter(config, meterReport, marketplaceConfig, prometheusAPI, v, dataBuilder, reportWriter)
	if err != nil {
		return nil, err
	}
	return marketplaceReporter, nil
}

var (
	_wireLogrLoggerValue = logger
)

func NewUploadTask(ctx context.Context, config *Config, namespace Namespace) (UploadRun, error) {
	logrLogger := _wireLoggerValue2
	restConfig := config.K8sRestConfig
	restMapper, err := managers.NewDynamicRESTMapper(restConfig)
	if err != nil {
		return nil, err
	}
	scheme := provideScheme()
	simpleClient, err := managers.ProvideSimpleClient(restConfig, restMapper, scheme)
	if err != nil {
		return nil, err
	}
	dataServiceConfig, err := provideDataServiceConfig(config)
	if err != nil {
		return nil, err
	}
	dataService, err := dataservice.NewDataService(dataServiceConfig)
	if err != nil {
		return nil, err
	}
	clientCommandRunner := reconcileutils.NewClientCommand(simpleClient, scheme, logrLogger)
	uploaders, err := ProvideUploaders(ctx, clientCommandRunner, simpleClient, logrLogger, config)
	if err != nil {
		return nil, err
	}
	uploadTask := &UploadTask{
		logger:      logrLogger,
		config:      config,
		k8SClient:   simpleClient,
		k8SScheme:   scheme,
		fileStorage: dataService,
		uploaders:   uploaders,
	}
	return uploadTask, nil
}

var (
	_wireLoggerValue2 = logger
)

func NewReconcileTask(ctx context.Context, config *Config, broadcaster record.EventBroadcaster, namespace Namespace, newReportTask func(ctx context.Context, reportName ReportName, taskConfig *Config) (TaskRun, error), newUploadTask func(ctx context.Context, config *Config, namespace Namespace) (UploadRun, error)) (*ReconcileTask, error) {
	logrLogger := _wireLoggerValue3
	restConfig := config.K8sRestConfig
	restMapper, err := managers.NewDynamicRESTMapper(restConfig)
	if err != nil {
		return nil, err
	}
	scheme := provideScheme()
	simpleClient, err := managers.ProvideSimpleClient(restConfig, restMapper, scheme)
	if err != nil {
		return nil, err
	}
	eventRecorder := provideReporterEventRecorder(broadcaster, scheme)
	reconcileTask := &ReconcileTask{
		logger:    logrLogger,
		K8SClient: simpleClient,
		Config:    config,
		K8SScheme: scheme,
		Namespace: namespace,
		recorder:  eventRecorder,
		NewTask:   newReportTask,
		NewUpload: newUploadTask,
	}
	return reconcileTask, nil
}

var (
	_wireLoggerValue3 = logger
)
