apiVersion: marketplace.redhat.com/v1beta1
kind: MeterDefinition
metadata:
  name: rhm-metric-state-uptime
spec:
  group: marketplace.redhat.com
  kind: Pod
  meters:
    - aggregation: avg
      metricId: rhm-metric-state-uptime
      name: rhm-metric-state-uptime
      period: 24h
      query: avg_over_time(up{job="rhm-metric-state-service"}[5m])
      workloadType: Pod
      metricType: infrastructure
  resourceFilters:
    - label:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: rhm-metric-state
      workloadType: Pod
