apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: rhm-metric-state-tls
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: rhm-metric-state
  name: rhm-metric-state-service
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: rhm-metric-state
  sessionAffinity: ClientIP
  type: ClusterIP
