apiVersion: apps/v1
kind: Deployment
metadata:
  name: remoteresource-controller
  annotations:
    # razee.io/git-repo: "{{{GIT_REMOTE}}}"
    # razee.io/commit-sha: "{{{TRAVIS_COMMIT}}}"
  labels:
    razee/watch-resource: "lite"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remoteresource-controller
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: remoteresource-controller
        razee/watch-resource: "lite"
      name: remoteresource-controller
    spec:
      serviceAccountName: razeedeploy-sa
      securityContext:
        runAsNonRoot: true
      containers:
        - name: authcheck
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8089
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 20m
              memory: 24Mi
            requests:
              cpu: 10m
              memory: 12Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true 
        - image: "quay.io/razee/remoteresource:2.1.11_bc34aa0"
          resources:
            limits:
              memory: 300Mi
              cpu: 200m
            requests:
              memory: 75Mi
              cpu: 50m
          env:
            - name: USER_AGENT_NAME
              value: razee-io/remoteresource
            - name: USER_AGENT_VERSION
              value: "2.1.11_bc34aa0"
            - name: RR_RECONCILE_BY_DEFAULT
              valueFrom:
                configMapKeyRef:
                  name: razeedeploy-overrides
                  key: RR_RECONCILE_BY_DEFAULT
                  optional: true
            - name: CRD_WATCH_TIMEOUT_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: razeedeploy-overrides
                  key: CRD_WATCH_TIMEOUT_SECONDS
                  optional: true
          imagePullPolicy: Always
          name: remoteresource-controller
          livenessProbe:
            exec:
              command:
                - sh/liveness.sh
            initialDelaySeconds: 30
            periodSeconds: 150
            timeoutSeconds: 30
            failureThreshold: 1
          volumeMounts:
            - mountPath: /home/node/download-cache
              name: cache-volume
            - mountPath: /home/node/config
              name: razeedeploy-config
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: razeedeploy-config
          configMap:
            name: razeedeploy-config
            defaultMode: 400
            optional: true
