// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package report

import (
	"github.com/redhat-marketplace/redhat-marketplace-operator/pkg/managers"
	"github.com/redhat-marketplace/redhat-marketplace-operator/pkg/reporter"
)

// Injectors from wire.go:

func initializeMarketplaceReporter(reportName reporter.ReporterName) (*reporter.MarketplaceReporter, error) {
	monitoringSchemeDefinition := managers.ProvideMonitoringScheme()
	v := provideMarketplaceReporterSchemes(monitoringSchemeDefinition)
	marketplaceReporterConfig, err := reporter.NewMarketplaceReporterConfig(reportName, v)
	if err != nil {
		return nil, err
	}
	marketplaceReporter, err := reporter.NewMarketplaceReporter(marketplaceReporterConfig)
	if err != nil {
		return nil, err
	}
	return marketplaceReporter, nil
}
