apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  selector:
    matchLabels:
      redhat.marketplace.com/name: redhat-marketplace-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        redhat.marketplace.com/name: redhat-marketplace-operator
        app.kubernetes.io/name: controller-manager
        app.kubernetes.io/instance: controller-manager
        app.kubernetes.io/part-of: redhat-marketplace-operator
        app.kubernetes.io/managed-by: operator
      annotations:
        productName: "Red Hat Marketplace Operator"
        productID: "36cdaba810c348c096b85800dd62bcf1"
        productMetric: "FREE"
    spec:
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - ppc64le
                    - s390x
      securityContext: 
        runAsNonRoot: true
      containers:
        - name: manager
          args:
            - --enable-leader-election
          image: redhat-marketplace-operator:latest
          resources:
            requests:
              cpu: 100m
              memory: 225Mi
            limits:
              cpu: 400m
              memory: 700Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: OPERATOR_NAME
              value: redhat-marketplace-operator
            - name: RELATED_IMAGE_AUTHCHECK
              value: redhat-marketplace-authcheck:latest
            - name: RELATED_IMAGE_RHM_RRS3_DEPLOYMENT
              value: us.icr.io/armada-master/remoteresource:2.1.19_7f655fe
            - name: RELATED_IMAGE_RHM_WATCH_KEEPER_DEPLOYMENT
              value: us.icr.io/armada-master/watch-keeper:0.8.10_7f655fe
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OLM_OWNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['olm.owner']
            - name: OLM_OWNER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['olm.owner.namespace']
            - name: OLM_OWNER_KIND
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['olm.owner.kind']
            - name: OPERATOR_GROUP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.operatorGroup']
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: manager
                  resource: limits.memory
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true   
      terminationGracePeriodSeconds: 10
      serviceAccountName: operator
