package controller

// Code generated by github.com/launchdarkly/go-options.  DO NOT EDIT.

import (
	"github.com/redhat-marketplace/redhat-marketplace-operator/v2/utils/pkg/reconcileutils"
)

type ApplyControllerOptionFunc func(c *controllerOptions) error

func (f ApplyControllerOptionFunc) apply(c *controllerOptions) error {
	return f(c)
}

func newControllerOptions(options ...ControllerOption) (controllerOptions, error) {
	var c controllerOptions
	err := applyControllerOptionsOptions(&c, options...)
	return c, err
}

func applyControllerOptionsOptions(c *controllerOptions, options ...ControllerOption) error {
	for _, o := range options {
		if err := o.apply(c); err != nil {
			return err
		}
	}
	return nil
}

type ControllerOption interface {
	apply(*controllerOptions) error
}

func ControllerOptionClientCommandProvider(o reconcileutils.ClientCommandRunnerProvider) ApplyControllerOptionFunc {
	return func(c *controllerOptions) error {
		c.ClientCommandProvider = o
		return nil
	}
}
