apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rhm-data-service
spec:
  selector:
    matchLabels:
      app: rhm-data-service
  serviceName: rhm-data-service
  replicas: 3
  template:
    metadata:
      labels:
        app: rhm-data-service
        app.kubernetes.io/name: rhm-data-service
        app.kubernetes.io/instance: rhm-data-service
        app.kubernetes.io/part-of: ibm-metrics-operator
        app.kubernetes.io/managed-by: operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - rhm-data-service
                namespaces:
                  - redhat-marketplace
                topologyKey: kubernetes.io/hostname
              weight: 100
      terminationGracePeriodSeconds: 45
      securityContext: 
        runAsNonRoot: true
      containers:
        - command: ['/bin/sh']
          args:
            [
              '-c',
              'if [ "$POD_NAME" != "rhm-data-service-0" ]; then DQLITE_JOIN="--join rhm-data-service-0.rhm-data-service.$POD_NAMESPACE.svc.cluster.local:9001"; fi; exec /usr/local/bin/entrypoint --ca-cert /etc/tls/private/ca.crt --tls-cert /etc/tls/private/tls.crt --tls-key /etc/tls/private/tls.key --db $POD_NAME.rhm-data-service.$POD_NAMESPACE.svc.cluster.local:9001 --dir /data -v $DQLITE_JOIN',
            ]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: redhat-marketplace-data-service
          imagePullPolicy: IfNotPresent
          name: rhm-data-service
          livenessProbe:
            exec:
              command:
                - grpc-health-probe
                - -addr=localhost:8003
            initialDelaySeconds: 60
            periodSeconds: 5
          ports:
            - containerPort: 9001
              name: db
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 25m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true 
          volumeMounts:
            - name: rhm-data-service
              mountPath: /data
            - mountPath: /etc/tls/private
              name: rhm-data-service-mtls
              readOnly: false
        - image: redhat-marketplace-authcheck
          imagePullPolicy: IfNotPresent
          name: authcheck
          resources:
            requests:
              cpu: 10m
              memory: 12Mi
            limits:
              cpu: 15m
              memory: 24Mi
          env:
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: authcheck
                resource: limits.memory
          terminationMessagePolicy: FallbackToLogsOnError
        - args:
            - --secure-listen-address=:8004
            - --tls-cipher-suites=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - --tls-min-version=VersionTLS12
            - --upstream=http://127.0.0.1:8003/
            - --upstream-force-h2c
            - --v=3
            - --tls-cert-file=/etc/tls/private/tls.crt
            - --tls-private-key-file=/etc/tls/private/tls.key
            - --auth-token-audiences=rhm-data-service,rhm-data-service.{{NAMESPACE}}.svc
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:latest
          imagePullPolicy: Always
          name: kube-rbac-proxy-1
          ports:
            - containerPort: 8004
              name: grpc
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
          env:
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: kube-rbac-proxy-1
                resource: limits.memory
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true 
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/tls/private
              name: rhm-data-service-tls
              readOnly: false
            - mountPath: /etc/configmaps/serving-cert-ca-bundle
              name: ibm-metrics-operator-serving-certs-ca-bundle
              readOnly: false
            - mountPath: /etc/tls/mtls
              name: rhm-data-service-mtls
              readOnly: false
        - args:
            - --secure-listen-address=:8008
            - --tls-cipher-suites=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - --tls-min-version=VersionTLS12
            - --upstream=http://127.0.0.1:8007/
            - --v=3
            - --tls-cert-file=/etc/tls/private/tls.crt
            - --tls-private-key-file=/etc/tls/private/tls.key
            - --auth-token-audiences=rhm-data-service,rhm-data-service.{{NAMESPACE}}.svc
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:latest
          imagePullPolicy: Always
          name: kube-rbac-proxy-2
          ports:
            - containerPort: 8008
              name: grpc
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
          env:
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: kube-rbac-proxy-2
                resource: limits.memory
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true 
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/tls/private
              name: rhm-data-service-tls
              readOnly: false
            - mountPath: /etc/configmaps/serving-cert-ca-bundle
              name: ibm-metrics-operator-serving-certs-ca-bundle
              readOnly: false
            - mountPath: /etc/tls/mtls
              name: rhm-data-service-mtls
              readOnly: false

      volumes:
        - name: rhm-data-service-tls
          secret:
            secretName: rhm-data-service-tls
        - name: rhm-data-service-mtls
          secret:
            secretName: rhm-data-service-mtls
        - configMap:
            name: ibm-metrics-operator-serving-certs-ca-bundle
          name: ibm-metrics-operator-serving-certs-ca-bundle
      serviceAccountName: ibm-metrics-operator-data-service
  volumeClaimTemplates:
    - metadata:
        name: rhm-data-service
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi
