// Copyright 2020 IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/redhat-marketplace/redhat-marketplace-operator/pkg/controller"
	"github.com/redhat-marketplace/redhat-marketplace-operator/pkg/managers"
)

// Injectors from wire.go:

func initializeMarketplaceController() *managers.ControllerMain {
	marketplaceController := controller.ProvideMarketplaceController()
	meterbaseController := controller.ProvideMeterbaseController()
	meterDefinitionController := controller.ProvideMeterDefinitionController()
	razeeDeployController := controller.ProvideRazeeDeployController()
	olmSubscriptionController := controller.ProvideOlmSubscriptionController()
	controllerFlagSet := controller.ProvideControllerFlagSet()
	opsSrcSchemeDefinition := managers.ProvideOpsSrcScheme()
	monitoringSchemeDefinition := managers.ProvideMonitoringScheme()
	olmV1SchemeDefinition := managers.ProvideOLMV1Scheme()
	olmV1Alpha1SchemeDefinition := managers.ProvideOLMV1Alpha1Scheme()
	controllerMain := makeMarketplaceController(marketplaceController, meterbaseController, meterDefinitionController, razeeDeployController, olmSubscriptionController, controllerFlagSet, opsSrcSchemeDefinition, monitoringSchemeDefinition, olmV1SchemeDefinition, olmV1Alpha1SchemeDefinition)
	return controllerMain
}
